import Vendor from '../models/Vendor.js'

const VENDORS = [
  { name:'Shutter Stories Photography', category:'Photography', location:'Mumbai, Maharashtra',
    description:'Award-winning wedding photographers capturing timeless love stories with cinematic flair, drone shots, and candid emotion. Over 500 weddings covered across India.',
    rating:4.9, priceRangeMin:45000, priceRangeMax:250000, isFeatured:true,
    imageUrl:'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=600&h=400&fit=crop&q=85',
    features:['HD Photo & Video','Same-day Highlights','Drone Shots','Online Gallery','Print Album','Pre-wedding Shoot'] },
  { name:'Royal Feast Catering', category:'Catering', location:'Delhi, NCR',
    description:'Multi-cuisine caterers serving 200–2000 guests with live counters, themed buffets and personalised menus. Trusted by royalty across India.',
    rating:4.8, priceRangeMin:800, priceRangeMax:3500, isFeatured:true,
    imageUrl:'https://images.unsplash.com/photo-1555244162-803834f70033?w=600&h=400&fit=crop&q=85',
    features:['Multi-cuisine Menu','Live Counters','Dessert Stations','Custom Menu','Service Staff','Hygiene Certified'] },
  { name:'Bloom & Blossom Decor', category:'Decoration', location:'Pune, Maharashtra',
    description:'Transforming venues into fairytale settings with fresh flowers, lighting magic and immersive themed setups. Featured in Vogue Weddings India.',
    rating:4.7, priceRangeMin:30000, priceRangeMax:500000, isFeatured:true,
    imageUrl:'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&h=400&fit=crop&q=85',
    features:['Floral Arrangements','LED Lighting','Stage Design','Mandap Decor','Photo Booths','Balloon Arch'] },
  { name:'The Grand Ballroom', category:'Venue', location:'Bangalore, Karnataka',
    description:'Luxury 5-star venue with a stunning 10,000 sq ft ballroom, manicured outdoor lawns, and world-class hospitality for up to 2000 guests.',
    rating:4.9, priceRangeMin:200000, priceRangeMax:2000000, isFeatured:true,
    imageUrl:'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600&h=400&fit=crop&q=85',
    features:['AC Ballroom','Outdoor Lawns','Bridal Suite','Valet Parking','In-house Catering','AV Equipment'] },
  { name:'Heritage Palace Venue', category:'Venue', location:'Udaipur, Rajasthan',
    description:'A stunning heritage palace on a shimmering lake offering royal Rajasthani hospitality for destination weddings that guests will never forget.',
    rating:5.0, priceRangeMin:500000, priceRangeMax:5000000, isFeatured:true,
    imageUrl:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop&q=85',
    features:['Lake View','Royal Suites','Heritage Architecture','In-house Decoration','Destination Wedding','Elephant Welcome'] },
  { name:'Beats & Vibes Entertainment', category:'Music', location:'Hyderabad, Telangana',
    description:'Professional DJ & live band services blending Bollywood, EDM and classical music for unforgettable celebrations that keep the dance floor packed.',
    rating:4.6, priceRangeMin:20000, priceRangeMax:120000, isFeatured:false,
    imageUrl:'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&h=400&fit=crop&q=85',
    features:['Professional DJ','Live Band Option','Sound System','Laser Lights','Custom Playlist','Dhol Players'] },
  { name:'Glam Studio by Priya', category:'Makeup', location:'Chennai, Tamil Nadu',
    description:'Celebrity bridal makeup artist with 12 years of experience. Creating flawless, long-lasting looks tailored to every skin tone and bridal vision.',
    rating:4.8, priceRangeMin:15000, priceRangeMax:80000, isFeatured:false,
    imageUrl:'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=400&fit=crop&q=85',
    features:['Bridal Makeup','Hair Styling','Trial Session','HD Makeup','Group Packages','Airbrush Finish'] },
  { name:'Henna Artistry by Zara', category:'Mehendi', location:'Jaipur, Rajasthan',
    description:'Traditional and contemporary mehendi designs by a master artist with 15 years of experience. From delicate Arabic patterns to intricate Rajasthani bridal art.',
    rating:4.9, priceRangeMin:5000, priceRangeMax:40000, isFeatured:false,
    imageUrl:'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=400&fit=crop&q=85',
    features:['Bridal Mehendi','Guest Mehendi','Arabic Designs','Traditional Motifs','Quick Dry Formula','Natural Paste'] },
  { name:'Elegant Print Invitations', category:'Invitations', location:'Ahmedabad, Gujarat',
    description:'Luxury custom wedding invitations — digital, printed, boxed and handcrafted for every budget. Featured in 200+ elite Indian weddings.',
    rating:4.7, priceRangeMin:2000, priceRangeMax:50000, isFeatured:false,
    imageUrl:'https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=600&h=400&fit=crop&q=85',
    features:['Custom Design','Digital Cards','Box Invites','RSVP Management','Gift Tags','Express Delivery'] },
  { name:'Candid Clicks Studio', category:'Photography', location:'Pune, Maharashtra',
    description:'Boutique photography studio specialising in candid wedding stories told through breathtaking stills and cinematic films.',
    rating:4.6, priceRangeMin:25000, priceRangeMax:150000, isFeatured:false,
    imageUrl:'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=600&h=400&fit=crop&q=85',
    features:['Candid Photography','Pre-wedding Shoot','Cinematic Video','Instagram Reels','Cloud Gallery','Same Day Edit'] },
  { name:'Spice Garden Caterers', category:'Catering', location:'Pune, Maharashtra',
    description:'Authentic Indian cuisine specialists with live tawa, chaat, and regional delicacy counters for large events. 100% hygienic, FSSAI certified.',
    rating:4.5, priceRangeMin:600, priceRangeMax:2000, isFeatured:false,
    imageUrl:'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&h=400&fit=crop&q=85',
    features:['North & South Indian','Live Tawa Counter','Chaat Station','Sweet Counter','Hygienic Service','FSSAI Certified'] },
  { name:'Dream Drape Decorators', category:'Decoration', location:'Mumbai, Maharashtra',
    description:'Specialist in luxury fabric draping, chandelier installations and minimalist-to-grand wedding aesthetics for 5-star venues.',
    rating:4.8, priceRangeMin:50000, priceRangeMax:800000, isFeatured:false,
    imageUrl:'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&h=400&fit=crop&q=85',
    features:['Fabric Draping','Chandeliers','Floral Walls','Backdrop Design','Entrance Arch','Floating Décor'] },
]

export async function seedVendors() {
  const count = await Vendor.countDocuments()
  if (count > 0) return
  await Vendor.insertMany(VENDORS)
  console.log(`✅ Seeded ${VENDORS.length} vendors with real images`)
}
